In [65]:
# -*- coding: utf-8 -*-
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# What is NumPy?
- NumPy stands for Numerical Python used for working with arrays.
- NumPy aims to provide an array object that is up to 50x faster that traditional Python lists. 
- Most of the parts of NumPy that require fast computation are written in C or C++.
- The array object in NumPy is called `ndarray`
- NumPy is often used along with SciPy (scientific python) and Matplotlib (for plotting). 

Source: https://www.tutorialspoint.com/numpy

In [66]:
import numpy as np
print(np.__version__)

1.23.3


In [67]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [68]:
type(arr)

numpy.ndarray

In [69]:
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

In [70]:
a = np.array([1, 2, 3, 4, 5], ndmin = 2) 
a

array([[1, 2, 3, 4, 5]])

## Shape and reshape

In [71]:
a = np.array([[1, 2, 3], [4, 5, 6]]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a.shape

(2, 3)

In [73]:
a = np.array([[1, 2, 3], [4, 5, 6]]) 
a.shape = (3, 2) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
a = np.array([[1, 2, 3], [4, 5, 6]]) 
b = a.reshape(3, 2) 
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [76]:
b = a.reshape(2, 4, 3) 
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [77]:


test = np.arange(27)
test.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

## Array from numerical ranges
**numpy.arange(start, stop, step, dtype)**

In [78]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [79]:
x = np.arange(5, dtype = float)
x

array([0., 1., 2., 3., 4.])

In [80]:
x = np.arange(10, 20, 2) 
x

array([10, 12, 14, 16, 18])

**numpy.linspace(start, stop, num, endpoint, retstep, dtype)**

In [81]:
x = np.linspace(10, 20, 5) 
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [82]:
x = np.linspace(10, 20, 5, endpoint = False)
x

array([10., 12., 14., 16., 18.])

## Indexing and Slicing
- items in ndarray object follows **zero-based index**
- indexing methods: field access, basic slicing and advanced indexing
- **slice object** is constructed by giving **start**, **stop**, and **step** parameters to the *built-in slice function*

In [83]:
a = np.arange(10) 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
s = slice(2, 7, 2) 
a[s]

array([2, 4, 6])

In [85]:
a = np.arange(10) 
b = a[2:7:2]
b

array([2, 4, 6])

### Slicing from index

In [86]:
a = np.arange(10) 
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [88]:
a[1:]

array([[3, 4, 5],
       [4, 5, 6]])

In [89]:
a[:1]

array([[1, 2, 3]])

### Advanced Indexing

In [90]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
y = x[[0, 1, 2], [0, 1, 0]]
y

array([1, 4, 5])

The selection *y* includes elements at (0,0), (1,1) and (2,0) from *x*.

### Boolean Array Indexing

In [92]:
x = np.array([[ 0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]) 
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [93]:
x[x > 5]

array([ 6,  7,  8,  9, 10, 11])

**NaN omitting**

In [94]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5]) 
a

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [95]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

## Broadcasting

In [96]:
a = np.array([1, 2, 3, 4]) 
a

array([1, 2, 3, 4])

In [97]:
b = np.array([10, 20, 30, 40])
b

array([10, 20, 30, 40])

In [98]:
c = a * b
c

array([ 10,  40,  90, 160])

**More complex example**

In [99]:
a = np.array([[0.0, 0.0, 0.0], [10.0, 10.0, 10.0], [20.0, 20.0, 20.0], [30.0, 30.0, 30.0]]) 
a

array([[ 0.,  0.,  0.],
       [10., 10., 10.],
       [20., 20., 20.],
       [30., 30., 30.]])

In [100]:
b = np.array([1.0, 2.0, 3.0]) 
b

array([1., 2., 3.])

In [101]:
c = a + b
c

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

<img src="https://www.tutorialspoint.com/numpy/images/array.jpg" />

## Iterating Over Array

In [102]:
a = np.arange(0, 60, 5) 
a = a.reshape(3, 4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [103]:
b = a.T 
b

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [104]:
for x in np.nditer(b): 
    print(x, end = ' ')

0 5 10 15 20 25 30 35 40 45 50 55 

**Another example**

In [105]:
a = np.arange(0,60, 5) 
a = a.reshape(3, 4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [106]:
b = np.array([1, 2, 3, 4], dtype = int) 
b

array([1, 2, 3, 4])

In [107]:
for x, y in np.nditer([a, b]): 
   print("%d:%d" % (x, y), end = ' ')

0:1 5:2 10:3 15:4 20:1 25:2 30:3 35:4 40:1 45:2 50:3 55:4 

## Statistical Functions
**Min, Max**

In [108]:
a = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [109]:
np.amin(a, axis=0)

array([2, 4, 3])

In [110]:
np.amin(a, axis=1)

array([3, 3, 2])

In [111]:
np.amin(a)

2

**Median**

In [112]:
a = np.array([[30, 65, 70], [80, 95, 10], [50, 90, 60]])
a

array([[30, 65, 70],
       [80, 95, 10],
       [50, 90, 60]])

In [113]:
np.median(a) 

65.0

In [114]:
np.median(a, axis=0)

array([50., 90., 60.])

In [115]:
np.median(a, axis=1)

array([65., 80., 60.])

**Mean**

In [116]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [117]:
np.mean(a)

3.6666666666666665

In [118]:
np.mean(a, axis=0)

array([2.66666667, 3.66666667, 4.66666667])

In [119]:
np.mean(a, axis=1)

array([2., 4., 5.])

**Variance**

In [120]:
np.var([1, 2, 3, 4])

1.25

**Standard Deviation**

In [121]:
np.std([1, 2, 3, 4])

1.118033988749895

## Arithmetic Operations
**Input arrays** for performing arithmetic operations such as add(), subtract(), multiply(), and divide() must be either of **the same shape** or should conform to array broadcasting rules.

In [122]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [123]:
b = np.array([10, 10, 10])
b

array([10, 10, 10])

In [124]:
np.add(a, b)

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [125]:
np.subtract(a, b)

array([[-10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.],
       [ -4.,  -3.,  -2.]])

In [126]:
np.multiply(a, b)

array([[ 0., 10., 20.],
       [30., 40., 50.],
       [60., 70., 80.]])

In [127]:
np.divide(a, b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])